### ISSUE TITLE
Windows error -utils.commons & : No module named 'inference.real3d_infer

### ISSUE THREAD

**Issue by Inferencer** [yerfor/Real3DPortrait#10]
Everything seemed to install fine
when running on windows 10 annaconda cuda 11.7
```
(real3dportrait) C:\Users\Jack\Real3DPortrait>python inference/app_real3dportrait.py
Traceback (most recent call last):
  File "C:\Users\Jack\Real3DPortrait\inference\app_real3dportrait.py", line 4, in <module>
    from inference.real3d_infer import GeneFace2Infer
ModuleNotFoundError: No module named 'inference.real3d_infer'
```

```
(real3dportrait) C:\Users\Jack\Real3DPortrait>python inference/real3d_infer.py --src_img C:\Users\Jack\Real3DPortrait\data\raw\examples\Macron.png --drv_aud C:\Users\Jack\Real3DPortrait\data\raw\exampleszObama_5s.wav
Traceback (most recent call last):
  File "C:\Users\Jack\Real3DPortrait\inference\real3d_infer.py", line 16, in <module>
    from utils.commons.hparams import hparams, set_hparams
ModuleNotFoundError: No module named 'utils.commons'
```

**Comment by yerfor** [comment]
please add the root directory of GeneFacePlusPlus into your `PYTHONPATH`

**Comment by Inferencer** [comment]
I'm not sure how to do that as when i try the export command in annaconda i get
```
'export' is not recognized as an internal or external command,
operable program or batch file.
```
I also tried
`(real3dportrait) C:\Users\Jack\Real3DPortrait>set PYTHONPATH=C:\Users\Jack\Real3DPortrait`

unless I'm misunderstanding and im supposed to be doing something else completely

**Comment by Marius-Heinrich** [comment]
I initially resolved this issue by directly setting the path to the project as an environment variable in Windows.

1. Type "env" in the Windows search bar.

2. Click on the first result in the search.

3. Click on "Environment Variables."

4. Create a new entry under "System variables."
Variable name: PYTHONPATH
Variable value: The path to your project folder.

It might not be perfect, but it gets the job done.

**Comment by Inferencer** [comment]
no luck I'm afraid, ill try user variables just in case but now ive been messing around with setting the path inside the conda env it could be messing with your solution

**Comment by yerfor** [comment]
Maybe you can add this line before importing other libs:
```
os.environ['PYTHONPATH'] = './'
```
> no luck I'm afraid, ill try user variables just in case but now ive been messing around with setting the path inside the conda env it could be messing with your solution
