### ISSUE TITLE
About the landmark extraction

### ISSUE THREAD

**Issue by stonewalking** [yerfor/Real3DPortrait#14]
Regarding about the landmark extraction, I am a bit curious about the perception in results compared with one hot off-the-shell method face alignment. 
Have the author try to use face alignment package before in the data processing experiments stage? Is there any superiority by Mediapipe Studio? Is there an trend that people start to use Mediapipe in the face market?

**Comment by yerfor** [comment]
Yes, we initially used face_alignment, but we found mediapipe is more accurate.
