### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by buddylee7** [yerfor/Real3DPortrait#15]
Inference ERROR: name 'MeshRasterizer' is not defined

**Comment by buddylee7** [comment]
| Extracted pose from C:\Users\Michael\AppData\Local\Temp\gradio\ea1ab761e00e431654ac8293a6d1e93a2a4ca7ef\May_5s.mp4
{'src_image_name': 'infer_out/tmp/cropped_src_img.png', 'drv_audio_name': 'C:\\Users\\Michael\\AppData\\Local\\Temp\\gradio\\10e38d2a0e8854b09cf1b695e2305e3219e729af\\Obama_5s.wav', 'drv_pose_name': 'C:\\Users\\Michael\\AppData\\Local\\Temp\\gradio\\ea1ab761e00e431654ac8293a6d1e93a2a4ca7ef\\May_5s.mp4', 'bg_image_name': 'C:\\Users\\Michael\\AppData\\Local\\Temp\\gradio\\77e40a84169eb20cd5632ed343840895826c8a11\\bg.png', 'blink_mode': 'none', 'temperature': 0.2, 'mouth_amp': 0.25, 'out_mode': 'final', 'map_to_init_pose': True, 'low_memory_usage': True, 'hold_eye_opened': True, 'a2m_ckpt': 'D:\\Real3DPortrait\\checkpoints\\240210_real3dportrait_orig\\audio2secc_vae\\model_ckpt_steps_400000.ckpt', 'head_ckpt': 'D:\\Real3DPortrait\\checkpoints\\240210_real3dportrait_orig\\audio2secc_vae\\model_ckpt_steps_400000.ckpt', 'torso_ckpt': 'D:\\Real3DPortrait\\checkpoints\\240210_real3dportrait_orig\\secc2plane_torso_orig\\model_ckpt_steps_100000.ckpt', 'min_face_area_percent': 0.22, 'out_name': '', 'seed': 42}
| audio-to-motion finished
rendering drv secc:   0%|                                                                        | 0/3 [00:00<?, ?it/s]
Inference ERROR: name 'MeshRasterizer' is not defined
Failed to generate

**Comment by yerfor** [comment]
Please check the installation of `pytorch3d`, which is the dependency of MeshRasterizer. See stdout above, there should be a MeshRasterizer ImportError.

**Comment by buddylee7** [comment]
That fixed it!  Thank you.  The command I ran was:  

pip install --no-index --no-cache-dir pytorch3d -f https://dl.fbaipublicfiles.com/pytorch3d/packaging/wheels/py38_cu113_pyt1110/download.html


NOTE:  Uploading an alternative image doesn't seem to work.  It continues to use the default.

**Comment by buddylee7** [comment]
Is there anything special you need to do in order to upload a new picture or driving video?  Certain requirements?  Or is there training involved?

**Comment by yerfor** [comment]
The image should be square, otherwise it will be resize to 512x512. The head should not be too small in the image.
