### ISSUE TITLE
推理的一些疑问

### ISSUE THREAD

**Issue by laishujie** [yerfor/Real3DPortrait#17]
你好，我使用了最新的代码以及模型“240210_real3dportrait_orig”来生成视频。在进行推理后，我遇到了几个问题：

**1.头发与身体分离**：在生成的视频中，头发与身体出现了分离的情况。特别是对于长发，是否存在解决方案或调整参数的方法来改善这一问题？

**2.牙齿模糊不清**：视频中牙齿的清晰度较低，影响了整体质量。我想了解是否需要重新训练模型或采取其他措施来提高牙齿部位的清晰度？

**3.视频质量与图片清晰度差距**：生成的视频质量与原始图片的清晰度相比有明显差距。您能否提供一些建议或方法，帮助我减小这种质量差异？

附上一张问题示例的截图以便更好地展示我的问题：

![image](https://github.com/yerfor/Real3DPortrait/assets/16934884/63aa7790-9988-4ade-91e5-258a117cee40)

**Comment by yerfor** [comment]
1. 这是NeRF的性质决定的。现阶段NeRF的解决方案没有办法处理长头发。
2&3. 可能是因为训练数据中清晰的牙齿数据太少导致的。可以通过gpen等超分模型提升画质。

**Comment by laishujie** [comment]
> Q1： 这是NeRF的性质决定的。现阶段NeRF的解决方案没有办法处理长头发。 Q2&3： 可能是因为训练数据中清晰的牙齿数据太少导致的。可以通过gpen等超分模型提升画质。

好的，谢谢。但是我在推理的时候还有两个小疑问

1.背景不完整，有分裂现象如何不改变？
2.眨眼的时候头部会被放大有时候会抽搐。

下面是我的推理图片和结果

![2](https://github.com/yerfor/Real3DPortrait/assets/16934884/19a4e38b-83b9-4114-a0c9-d0ebf0f9a5fe)


https://github.com/yerfor/Real3DPortrait/assets/16934884/ff2bd76f-6559-457c-87a2-cdd9cb92c4a4
