### ISSUE TITLE
body blurry 

### ISSUE THREAD

**Issue by z89685413** [yerfor/Real3DPortrait#2]
great project
i used only audio-driven, got result from gradio UI, the output body is blurry.
any help would be appreciated
<img width="382" alt="截屏2024-02-04 下午4 36 55" src="https://github.com/yerfor/Real3DPortrait/assets/52489076/0bffa38f-0a03-4f47-ac52-f4559639b35e">

**Comment by yerfor** [comment]
hi, can you upload the source image so we could reproduce the bug.

**Comment by yerfor** [comment]
Hi, we have uploaded the new checkpoint that could handle the mentioned problems to the cloud drive. You can get them in the shared link provided in the README.md
