### ISSUE TITLE
眨眼引发头部抽动问题

### ISSUE THREAD

**Issue by wangchenwc** [yerfor/Real3DPortrait#20]
大佬，引入眨眼动作，头部会有抽动的动作，去掉眨眼动作，抽动就消失了。

感觉和sadtalker一样的问题。是blink系数和头部pose系数没有完全解耦么？

**Comment by Kizuna-AII** [comment]
We also observed this problem and have a similar guess as you that the blink control is not well disentangled with pose or expression.
Thanks for your helpful thinking of our work!

**Comment by xiao-keeplearning** [comment]
大佬好，我发现有些动作下眨眼抽动较小，有些动作眨眼头部就非常不自然，有考虑过怎么优化么
