### ISSUE TITLE
Real time inference

### ISSUE THREAD

**Issue by mrtpk** [yerfor/Real3DPortrait#21]
Can we use this method to generate realtime inference?

**Comment by Kizuna-AII** [comment]
In our test environment (NVIDIA V100), the speed of video rendering is about 6~7 frames per second, I think it is not simple for Real3DPortrait to achieve realtime inference

**Comment by mrtpk** [comment]
Thank you for your response

**Comment by felixshing** [comment]
This is the inference speed in my 4090 GPU

<img width="1346" alt="image" src="https://github.com/yerfor/Real3DPortrait/assets/61814345/27a74e14-37b7-4467-9c48-dd510d795b5a">

it is almost real time. Any potential solution to further accelerate it?
