### ISSUE TITLE
你好，关于背景丢失的问题

### ISSUE THREAD

**Issue by laishujie** [yerfor/Real3DPortrait#23]
这是我的推理图片
![图片](https://github.com/yerfor/Real3DPortrait/assets/16934884/b22d31f4-b3f8-4f65-a571-ae8a535754e1)
这是推理结果：

https://github.com/yerfor/Real3DPortrait/assets/16934884/7a648d12-5a19-48dc-ba07-885f4e003f72

人物右边的背景没了，这个用gpen等超分模型也还原不回来了吧0v0.，有什么方法可以不改动背景吗？

**Comment by yerfor** [comment]
你好，你可以用代码提供的segmenter对原图做一下segment导出segmap，看看是不是这部分图像被识别成了背景以外的区域（比如torso）。如果是这个原因，可以尝试替换精度更高的segmenter。

**Comment by laishujie** [comment]
> 你好，你可以用代码提供的segmenter对原图做一下segment导出segmap，看看是不是这部分图像被识别成了背景以外的区域（比如torso）。如果是这个原因，可以尝试替换精度更高的segmenter。

好，那我知道原因了，谢谢。
