### ISSUE TITLE
是否可以驱动中文音频呢

### ISSUE THREAD

**Issue by luhairong11** [yerfor/Real3DPortrait#24]
是否可以驱动中文音频呢，我在测试的时候，英文的音频可以，改成中文音频，则没有声音

**Comment by Kizuna-AII** [comment]
Hi, we have just tested some Chinese audio samples and believe that Real3DPortrait is able to generate talking heads with various languages including Chinese.
I am not very clear what's the meaning of "no sound", is the generated lip not synced with audio?
And please make sure that the input audio file path should not contain non-english characters.
