### ISSUE TITLE
你好，眨眼范围的修改问题想请教是什么原因

### ISSUE THREAD

**Issue by laishujie** [yerfor/Real3DPortrait#27]
这是我的素材
![cropped_src_img](https://github.com/yerfor/Real3DPortrait/assets/16934884/30e35e7d-2360-4e16-b267-1a10121b1ac7)
这是生成的结果截图：
![1](https://github.com/yerfor/Real3DPortrait/assets/16934884/502f5fa7-586b-44f5-bdd0-1d129c5ba1ee)

一些3d动漫的人物眼睛就无法闭合，我怀疑是眼睛区域太小导致了，所以我修改了eye_mask
edit_secc.py
``` python
def blink_eye_for_secc(img, close_eye_percent=0.5):
    ....
   # 改为固定测试
    mask_img = cv2.imread('inference/eye_mask.png', cv2.IMREAD_GRAYSCALE)
    eye_mask = (mask_img > 0) 
 ``` 
测试的结果是:

https://github.com/yerfor/Real3DPortrait/assets/16934884/1910d2d5-f1c2-4c78-9e1b-cbae9f5dbdc7

眼睛蒙版区域已经修改了，但,生成的时候却没效果.

https://github.com/yerfor/Real3DPortrait/assets/16934884/42d1ee44-a6b9-4424-ba7d-5a684b0948b3

1.支持这种3d人物的眨眼或者一些眼睛大的
2.牙齿的话是训练数据中清晰的牙齿数据太少导致的,但整体画面**模糊**，感官上还不如256*256的清晰，但使用GFPGAN增强画质，会丢失一些细节。
这两个问题是目前是无法修改的吗？谢谢

**Comment by yerfor** [comment]
你好，我们的训练数据里没有3D人物，所以效果会有一些下降。
