### ISSUE TITLE
Network architecture of I2P and MA modules

### ISSUE THREAD

**Issue by trThanhnguyen** [yerfor/Real3DPortrait#29]
Hi, authors. Thanks for sharing your work.
Can you explain the reason for the design of the I2P and MA modules? The MA looks like a ViT branch in the I2P, why it does not have the VGG branch as well?
![image](https://github.com/yerfor/Real3DPortrait/assets/113072027/3d5c147f-0012-4739-80a4-41140146531e)

**Comment by yerfor** [comment]
Hi, 

The I2P model aims at reconstruting a accurate 3D face representation with rich geometry and texture details, so we use a hybrid artecture of VGG and ViT. I2P is a large model that have >80M parameters.

By contrast, the MA only aims at learning the geometry difference needed to control the expression, so we use an efficient archtecture, SegFormer-b0, which is parameter-light.
