### ISSUE TITLE
你好，长音频推理CUDA out of memory

### ISSUE THREAD

**Issue by laishujie** [yerfor/Real3DPortrait#3]
你好，我在使用我的机器（具有12GB显存）进行推理时遇到了显存问题。当我尝试使用一段长达25秒的音频进行推理时，我的程序直接报错 "CUDA out of memory"。
![17070360315374](https://github.com/yerfor/Real3DPortrait/assets/16934884/8c987bcb-fb24-4cf7-b070-7885148eee63)

我尝试过调整，但仍然遇到相同的问题。我预想的结果是能够成功使用长音频进行推理。

请问有什么解决方法克服这个显存问题吗？

非常感谢您的帮助！

**Comment by yerfor** [comment]
你好，我们会在近日更新inference代码以优化显存的占用，感谢指出这个问题。
