### ISSUE TITLE
Audio-driven head pose

### ISSUE THREAD

**Issue by trThanhnguyen** [yerfor/Real3DPortrait#30]
Hi, thank you for sharing your work.
I notice that this method requires a driving video, as in the argument setting in line 591, ./inference/real3d_infer.py:
```
parser.add_argument("--drv_pose", default='data/raw/examples/May_5s.mp4', type=str) # data/raw/examples/May_5s.mp4
```
Please help me on how to use the predicted pose from the A2M.
Thank you.

**Comment by Kizuna-AII** [comment]
If ```drv_audio_name``` is set to be an audio file, the drv_pose only provides ```camera pose``` (i.e. translation & rotation), and the A2M module will predict ```expression``` from the given audio.

**Comment by trThanhnguyen** [comment]
Ok, thanks.
