### ISSUE TITLE
colab demo can not access checkpoint in google driver 

### ISSUE THREAD

**Issue by ywaby** [yerfor/Real3DPortrait#36]
err info
```
Failed to retrieve file url:

	Cannot retrieve the public link of the file. You may need to change
	the permission to 'Anyone with the link', or have had many accesses.

You may still be able to access the file from the browser:

	https://drive.google.com/uc?id=1SPM3IHsyNAaVMwqZZGV6QVaV7I2Hly0v

but Gdown can't. Please check connections and permissions.
...
```

**Comment by Wasim1234566** [comment]
I have the same error, for the same project. Previously, I encountered the same error and running the command "pip install --upgrade --no-cache-dir gdown"fixed it. Recently, this command is not working anymore, and it's starting to throw errors again.You can try it.

**Comment by ywaby** [comment]
> I have the same error, for the same project. Previously, I encountered the same error and running the command "pip install --upgrade --no-cache-dir gdown"fixed it. Recently, this command is not working anymore, and it's starting to throw errors again.You can try it.

YES,It's fixed,Thanks.
