### ISSUE TITLE
bad result

### ISSUE THREAD

**Issue by zdyshine** [yerfor/Real3DPortrait#4]
Input has audio,ref video and ref image.The image is the first frame in the video.    
any suggestions？

**Comment by zdyshine** [comment]
<img width="727" alt="微信图片_20240205160616" src="https://github.com/yerfor/Real3DPortrait/assets/35593072/4b1c1905-b154-4c57-8fb0-657f3192b570">

**Comment by yerfor** [comment]
Hi, could you crop the face as the source image so the face region could be more large in the input. Maybe it is due to the fact that the uploaded checkpoint is only trained with videos with large face. I will update the checkpoint trained with uncropped frames in the future.

**Comment by zdyshine** [comment]
After conducting various tests, I found that the input image needs to be a human face and similar in size to the faces in the video for the effect to appear natural. In other cases, there are more or less issues.

**Comment by yerfor** [comment]
About the relationship between image and driving pose video, maybe you could turn on `map_to_init_pose`, which is now set to default in the latest commit, which could alleviate the mismatch in source image and driving head pose.

**Comment by yerfor** [comment]
Hi, we have uploaded the new checkpoint that could handle the mentioned problems to the cloud drive. You can get them in the shared link provided in the README.md
