### ISSUE TITLE
头发缺失

### ISSUE THREAD

**Issue by 1184919257** [yerfor/Real3DPortrait#41]
分割没有问题，但推理后的图像头发区域缺失
https://github.com/yerfor/Real3DPortrait/assets/32363554/85d8cde6-edfd-4161-9d22-917f9dc629b1
![2024-03-20_10-23-12-580540](https://github.com/yerfor/Real3DPortrait/assets/32363554/eedd5d24-5744-433f-9176-5ad464fcba77)

**Comment by yerfor** [comment]
Hi，可以尝试使用其他的segmenter；此外换成正脸图片作为输入可以获得更好的3D重建人脸。
