### ISSUE TITLE
PyTorch3D 安装失败

### ISSUE THREAD

**Issue by AspadaX** [yerfor/Real3DPortrait#43]
(geneface) root@xinyuhome:/home/xinyubao/Real3DPortrait# conda install pytorch3d::pytorch3d
Retrieving notices: ...working... done
Collecting package metadata (current_repodata.json): done
Solving environment: unsuccessful initial attempt using frozen solve. Retrying with flexible solve.
Solving environment: unsuccessful attempt using repodata from current_repodata.json, retrying with next repodata source.
Collecting package metadata (repodata.json): done
Solving environment: unsuccessful initial attempt using frozen solve. Retrying with flexible solve.
Solving environment: - 
Found conflicts! Looking for incompatible packages.
This can take several minutes.  Press CTRL-C to abort.
failed                                                                                                                                                                

UnsatisfiableError: The following specifications were found
to be incompatible with the existing python installation in your environment:

Specifications:

  - pytorch3d::pytorch3d -> python[version='>=2.7,<2.8.0a0|>=3.12,<3.13.0a0|>=3.5,<3.6.0a0']

Your python: python=3.9

If python is on the left-most side of the chain, that's the version you've asked for.
When python appears to the right, that indicates that the thing on the left is somehow
not available for the python version you are constrained to. Note that conda will not
change your python version to a different minor version unless you explicitly specify
that.

The following specifications were found to be incompatible with your system:

  - feature:/linux-64::__cuda==11.4=0
  - feature:/linux-64::__glibc==2.35=0
  - feature:|@/linux-64::__cuda==11.4=0
  - feature:|@/linux-64::__glibc==2.35=0
  - pytorch3d::pytorch3d -> pytorch==2.0.1 -> __cuda[version='>=11.8']
  - pytorch3d::pytorch3d -> torchvision[version='>=0.5'] -> __glibc[version='>=2.17,<3.0.a0']

Your installed version is: 2.35

教程里面要装 Python 3.9 ，但我 3.9 在 Ubuntu 机器上安装 PyTorch3D 直接失败，说版本不符合要求？

**Comment by yerfor** [comment]
可以尝试pip+git的方式安装，直接从源码build，虽然编译比较慢，但是成功率最高。
