### ISSUE TITLE
这个和GeneFacePlusPlus有什么区别呢？

### ISSUE THREAD

**Issue by shinerdeng** [yerfor/Real3DPortrait#44]
GeneFacePlusPlus用视频训练nerf模型，再用音频驱动。
这个直接用图片和音视频驱动？不知道理解对不对

**Comment by yerfor** [comment]
是的，GeneFace++是在单个视频上overfit一个小模型；Real3D-Portrait是预训练了一个通用模型，只需要单张图片不需要训练网络即可生成视频。
