### ISSUE TITLE
warn info

### ISSUE THREAD

**Issue by wangchenwc** [yerfor/Real3DPortrait#5]
WARN: egs/egs_bases/audio2motion/vae.yaml not exist.
| WARN: checkpoints/240126_real3dportrait_orig/th1kh_512_audio2motion/base.yaml not exist.
| load 'model' from 'checkpoints/240126_real3dportrait_orig/audio2secc_vae/model_ckpt_steps_400000.ckpt', strict=True
| WARN: checkpoints/240126_real3dportrait_orig/secc2plane_torso_orig/secc_img2plane_orig.yaml not exist.
INFO:torch.distributed.nn.jit.instantiator:Created a temporary directory at /tmp/tmplt00ie8x
INFO:torch.distributed.nn.jit.instantiator:Writing /tmp/tmplt00ie8x/_remote_module_non_scriptable.py
| load 'model' from 'checkpoints/240126_real3dportrait_orig/secc2plane_torso_orig/model_ckpt_steps_100000.ckpt', strict=False

**Comment by Kizuna-AII** [comment]
Hi, these warnings should be harmless during the inference stage. 
Since all the hyper-parameters are provided in the `config.yaml `, there is no need for loading the parent configuration file.
