### ISSUE TITLE
bad result in tooth?

### ISSUE THREAD

**Issue by wangchenwc** [yerfor/Real3DPortrait#6]

**Comment by wangchenwc** [comment]
https://github.com/yerfor/Real3DPortrait/assets/41559810/8c95927c-663d-471d-9bd8-15b3a937e94d

**Comment by wangchenwc** [comment]
同时眼睛眨眼，只能眨到一半么？

**Comment by yerfor** [comment]
Hi, we have uploaded the new checkpoint that could handle the mentioned problems to the cloud drive. You can get them in the shared link provided in the README.md
