### ISSUE TITLE
想请教一下大佬，该如何添加眨眼的效果

### ISSUE THREAD

**Issue by gongfusanhao** [yerfor/Real3DPortrait#9]
用图片生成的数字人好像不会眨眼，请问有什么方法能添加眨眼嘛？

**Comment by yerfor** [comment]
按照目前的setting，应该每隔5秒钟会眨眼一次。可以在real3d_infer.py文件中搜索`inp['blink_mode']`。我在本地尝试了很多identity都可以实现眨眼。

**Comment by gongfusanhao** [comment]
请问这个眨眼的频率和drv_pose视频中的的人物的眨眼频率有关吗？

**Comment by gongfusanhao** [comment]
还有，大佬我想问问drv_pose有什么具体的要求吗？

**Comment by gongfusanhao** [comment]
眨眼的问题已经解决了，在inference.py里面把--blink_mode改成period就行。谢谢大佬

**Comment by yerfor** [comment]
你好，drv_pose视频没有具体要求，一般建议将`map_to_init_pose`设置为True（默认是True）来得到较自然的结果。

**Comment by gongfusanhao** [comment]
有关drv_pos的条件，是不是一定要是512*512，人像在中间？

**Comment by yerfor** [comment]
不一定要人像在中间，人像位置不关键。关于分辨率，代码应该会把视频画面自动resize到512x512。所以如果是长方形的画面，可能会有画面畸变导致的一些精度下降问题。
